// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsycmgavhvxmduaotfua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzeWNtZ2F2aHZ4bWR1YW90ZnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODgyOTksImV4cCI6MjA2NDY2NDI5OX0.P8hL8DF20Ig4TU6n8KyMz4XVzudqueU_GhbAG5YWbtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);